"""
    eHelply SDK - 1.1.97

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.97
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.projects_usage_type_unit_price import ProjectsUsageTypeUnitPrice
globals()['ProjectsUsageTypeUnitPrice'] = ProjectsUsageTypeUnitPrice
from ehelply_python_sdk.model.projects_usage_type_create import ProjectsUsageTypeCreate


class TestProjectsUsageTypeCreate(unittest.TestCase):
    """ProjectsUsageTypeCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectsUsageTypeCreate(self):
        """Test ProjectsUsageTypeCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectsUsageTypeCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
