"""
    eHelply SDK - 1.1.121

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.121
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.service_super_stack_meta_faq import ServiceSuperStackMetaFaq
from ehelply_python_sdk.model.service_super_stack_meta_feature import ServiceSuperStackMetaFeature
from ehelply_python_sdk.model.service_super_stack_meta_getting_started import ServiceSuperStackMetaGettingStarted
from ehelply_python_sdk.model.service_super_stack_meta_use_case import ServiceSuperStackMetaUseCase
globals()['ServiceSuperStackMetaFaq'] = ServiceSuperStackMetaFaq
globals()['ServiceSuperStackMetaFeature'] = ServiceSuperStackMetaFeature
globals()['ServiceSuperStackMetaGettingStarted'] = ServiceSuperStackMetaGettingStarted
globals()['ServiceSuperStackMetaUseCase'] = ServiceSuperStackMetaUseCase
from ehelply_python_sdk.model.service_super_stack_meta import ServiceSuperStackMeta


class TestServiceSuperStackMeta(unittest.TestCase):
    """ServiceSuperStackMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceSuperStackMeta(self):
        """Test ServiceSuperStackMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServiceSuperStackMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
