"""
    eHelply SDK - 1.1.119

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.119
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.contact_method import ContactMethod
globals()['ContactMethod'] = ContactMethod
from ehelply_python_sdk.model.contact_base import ContactBase


class TestContactBase(unittest.TestCase):
    """ContactBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactBase(self):
        """Test ContactBase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContactBase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
