"""
    eHelply SDK - 1.1.110

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.110
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.discount import Discount


class TestDiscount(unittest.TestCase):
    """Discount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiscount(self):
        """Test Discount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Discount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
