"""
    eHelply SDK - 1.1.97

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.97
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.user_token_return import UserTokenReturn


class TestUserTokenReturn(unittest.TestCase):
    """UserTokenReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserTokenReturn(self):
        """Test UserTokenReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserTokenReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
