"""
    eHelply SDK - 1.1.118

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.118
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.create_field200_response import CreateField200Response


class TestCreateField200Response(unittest.TestCase):
    """CreateField200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateField200Response(self):
        """Test CreateField200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateField200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
