"""
    eHelply SDK - 1.1.100

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.100
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.address_base import AddressBase
from ehelply_python_sdk.model.category_base import CategoryBase
from ehelply_python_sdk.model.company import Company
from ehelply_python_sdk.model.contact_base import ContactBase
from ehelply_python_sdk.model.tag_base import TagBase
globals()['AddressBase'] = AddressBase
globals()['CategoryBase'] = CategoryBase
globals()['Company'] = Company
globals()['ContactBase'] = ContactBase
globals()['TagBase'] = TagBase
from ehelply_python_sdk.model.place_response import PlaceResponse


class TestPlaceResponse(unittest.TestCase):
    """PlaceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlaceResponse(self):
        """Test PlaceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlaceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
