"""
    eHelply SDK - 1.1.111

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.111
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.delete_file200_response import DeleteFile200Response


class TestDeleteFile200Response(unittest.TestCase):
    """DeleteFile200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteFile200Response(self):
        """Test DeleteFile200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteFile200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
