"""
    eHelply SDK - 1.1.115

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.115
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.update_field200_response import UpdateField200Response


class TestUpdateField200Response(unittest.TestCase):
    """UpdateField200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateField200Response(self):
        """Test UpdateField200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateField200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
