"""
    eHelply SDK - 1.1.116

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.116
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.create_meta200_response import CreateMeta200Response


class TestCreateMeta200Response(unittest.TestCase):
    """CreateMeta200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateMeta200Response(self):
        """Test CreateMeta200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateMeta200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
