"""
    eHelply SDK - 1.1.112

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.112
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.basic import Basic
from ehelply_python_sdk.model.dates import Dates
from ehelply_python_sdk.model.detailed import Detailed
from ehelply_python_sdk.model.field import Field
globals()['Basic'] = Basic
globals()['Dates'] = Dates
globals()['Detailed'] = Detailed
globals()['Field'] = Field
from ehelply_python_sdk.model.meta_dynamo import MetaDynamo


class TestMetaDynamo(unittest.TestCase):
    """MetaDynamo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetaDynamo(self):
        """Test MetaDynamo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetaDynamo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
