"""
    eHelply SDK - 1.1.120

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.120
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.save_fact200_response import SaveFact200Response


class TestSaveFact200Response(unittest.TestCase):
    """SaveFact200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveFact200Response(self):
        """Test SaveFact200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SaveFact200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
