"""
    eHelply SDK - 1.1.101

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.101
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.update_review import UpdateReview


class TestUpdateReview(unittest.TestCase):
    """UpdateReview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateReview(self):
        """Test UpdateReview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateReview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
