"""
    eHelply SDK - 1.1.119

    eHelply SDK for SuperStack Services  # noqa: E501

    The version of the OpenAPI document: 1.1.119
    Contact: support@ehelply.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ehelply_python_sdk
from ehelply_python_sdk.model.delete_meta200_response import DeleteMeta200Response


class TestDeleteMeta200Response(unittest.TestCase):
    """DeleteMeta200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteMeta200Response(self):
        """Test DeleteMeta200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteMeta200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
